swagger: "2.0"
info:
  title: Phase 2 of the Bank Argent API documentation
  description: Contains the conceptualized `/transactions/` route for the API
  version: "1.0.0"
  termsOfService: http://swagger.io/terms/

host: localhost:3001
basePath: /api/v1
schemes:
  - http

paths:
  /auth/login:
    post:
      tags:
        - Authentication
      summary: User login
      description: Authenticate user and return a JWT token
      parameters:
        - in: body
          name: login
          description: User login credentials
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
      produces:
        - application/json
      responses:
        "200":
          description: Login successful
          schema:
            type: object
            properties:
              token:
                type: string
        "400":
          description: Invalid username or password

  /auth/logout:
    post:
      tags:
        - Authentication
      summary: User logout
      description: Logout user by invalidating the JWT token
      parameters:
        - in: header
          name: Authorization
          description: "Bearer [JWT]"
          required: true
          type: string
      responses:
        "200":
          description: Logout successful
        "401":
          description: Unauthorized

  /auth/register:
    post:
      tags:
        - Authentication
      summary: User registration
      description: Register a new user
      parameters:
        - in: body
          name: registration
          description: User registration details
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
              email:
                type: string
      produces:
        - application/json
      responses:
        "201":
          description: Registration successful
        "400":
          description: Invalid input

  /{accountId}/transactions/:
    get:
      tags:
        - Transactions Module
      summary: Account transactions
      description: API to fetch the user account(s)'s transactions
      parameters:
        - in: header
          name: Authorization
          description: "Bearer [JWT]"
          required: true
          type: string
        - in: path
          name: accountId
          type: string
          description: ID of the account
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/TransactionsResponse"
        "400":
          description: Bad request
        "401":
          description: Unauthenticated
        "403":
          description: Unauthorized
        "404":
          description: Not found
        "500":
          description: Internal Server Error

  /{accountId}/transactions/{transactionId}/:
    get:
      tags:
        - Transactions Module
      summary: Account's singular transaction
      description: API to fetch a particular transaction
      parameters:
        - in: header
          name: Authorization
          description: "Bearer [JWT]"
          required: true
          type: string
        - in: path
          name: accountId
          type: string
          description: ID of the account
          required: true
        - in: path
          name: transactionId
          type: string
          description: ID of the transaction
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/TransactionIdResponse"
        "400":
          description: Bad request
        "401":
          description: Unauthenticated
        "403":
          description: Unauthorized
        "404":
          description: Not found
        "500":
          description: Internal Server Error

    post:
      tags:
        - Transactions Module
      summary: Creates transaction info
      description: Creates a note for the transaction
      parameters:
        - in: header
          name: Authorization
          description: "Bearer [JWT]"
          required: true
          type: string
        - in: path
          name: accountId
          type: string
          description: ID of the account
          required: true
        - in: path
          name: transactionId
          type: string
          description: ID of the transaction
          required: true
        - in: body
          name: Body of the request
          description: Adds notes to the transaction
          required: true
          schema:
            $ref: "#/definitions/TransactionsOtherPost"
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/TransactionsOtherPostResponse"
        "400":
          description: Bad request
        "401":
          description: Unauthenticated
        "403":
          description: Unauthorized
        "404":
          description: Not found
        "500":
          description: Internal Server Error

    put:
      tags:
        - Transactions Module
      summary: Changes transaction infos
      description: Changes the notes or the category of the transaction
      parameters:
        - in: header
          name: Authorization
          description: "Bearer [JWT]"
          required: true
          type: string
        - in: path
          name: accountId
          type: string
          description: ID of the account
          required: true
        - in: path
          name: transactionId
          type: string
          description: ID of the transaction
          required: true
        - in: body
          name: Body of the request
          description: Changes the notes and/or the category of the transaction
          required: true
          schema:
            $ref: "#/definitions/TransactionsOtherPut"
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/TransactionsOtherPutResponse"
        "400":
          description: Bad request
        "401":
          description: Unauthenticated
        "403":
          description: Unauthorized
        "404":
          description: Not found
        "500":
          description: Internal Server Error

    delete:
      tags:
        - Transactions Module
      summary: Deletes transaction infos
      description: Deletes the notes or the category of the transaction
      parameters:
        - in: header
          name: Authorization
          description: "Bearer [JWT]"
          required: true
          type: string
        - in: path
          name: accountId
          type: string
          description: ID of the account
          required: true
        - in: path
          name: transactionId
          type: string
          description: ID of the transaction
          required: true
        - in: body
          name: Body of the request
          description: Deletes the notes and/or the category
          required: true
          schema:
            $ref: "#/definitions/TransactionsOtherDelete"
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/TransactionsOtherDeleteResponse"
        "400":
          description: Bad request
        "401":
          description: Unauthenticated
        "403":
          description: Unauthorized
        "404":
          description: Not found
        "500":
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  Transactions:
    properties:
      accountId:
        type: string
        description: ID of the account
  TransactionsResponse:
    type: array
    items:
      type: object
      properties:
        transactionId:
          type: string
          description: ID of a transaction
        date:
          type: string
          description: Date of the transaction
        description:
          type: string
          description: Description of the transaction
        amount:
          type: number
          description: Amount spent in the transaction
        balance:
          type: number
          description: Account's balance after the transaction
  TransactionId:
    properties:
      accountId:
        type: string
        description: ID of the account
      transactionId:
        type: string
        description: ID of the transaction
  TransactionIdResponse:
    properties:
      transactionId:
        type: string
        description: ID of a transaction
      date:
        type: string
        description: Date of the transaction
      description:
        type: string
        description: Description of the transaction
      amount:
        type: number
        description: Amount spent in the transaction
      balance:
        type: number
        description: Account's balance after the transaction
      transactionType:
        type: string
        description: Type of payment for the transaction
      category:
        type: string
        description: Category of the transaction
      notes:
        type: string
        description: User notes of the transaction
  TransactionsOtherPost:
    properties:
      accountId:
        type: string
        description: ID of the account
      transactionId:
        type: string
        description: ID of the transaction
      notes:
        type: string
        description: Notes of the transaction
  TransactionsOtherPostResponse:
    properties:
      message:
        type: string
        description: Message of success
  TransactionsOtherPut:
    properties:
      accountId:
        type: string
        description: ID of the account
      transactionId:
        type: string
        description: ID of the transaction
      notes:
        type: string
        description: Notes of the transaction
      category:
        type: string
        description: Category of the transaction
  TransactionsOtherPutResponse:
    properties:
      message:
        type: string
        description: Message of success
  TransactionsOtherDelete:
    properties:
      accountId:
        type: string
        description: ID of the account
      transactionId:
        type: string
        description: ID of the transaction
      notes:
        type: boolean
        description: Boolean to know if notes should be deleted
      category:
        type: boolean
        description: Boolean to know if category should be deleted
  TransactionsOtherDeleteResponse:
    properties:
      message:
        type: string
        description: Message of success
